version: "3.8"
services:
  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  server:
    container_name: server
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3001:3001"
      - "3002:3002"
    stdin_open: true
    tty: true